name: experiments
root: ./

windows:
  - roscore:
      layout: even-vertical
      synchronize: after
      panes:
        - roscore
  - cameras:
      layout: even-vertical
      panes:
        - roslaunch piloting_core cam_front.launch
        - roslaunch piloting_core cam_down.launch
        - roslaunch piloting_core depth_camera.launch
  - leica:
      layout: even-vertical
      panes:
        - roslaunch piloting_core leica_pose.launch
  - rosbag:
      layout: even-vertical
      panes: 
       - 
       - 

